### ISSUE TITLE
ウイキの誤り

### ISSUE THREAD

**Issue by Tanimodori** [kobalab/majiang-core#2]
* [Majiang.Player#get-shan](https://github.com/kobalab/majiang-core/wiki/Majiang.Player#get-shan) に「牌山をを返す。」->「牌山を返す。」
* [牌譜#fenpei](https://github.com/kobalab/majiang-core/wiki/牌譜#fenpei)に「fenpai」->「fenpei」
* 「副露」のピンインの件について、「露」は「lù」と「lòu」二つの発音を持つ。日本語で「副露」は「フーロ」と読んでいる、しかし中国語で「副露」は「fù lòu」てはなく「fù lù」と読んでいる。中国語で「文白異読」という発音現象は存在している、つまり一つの漢字は二つの発音を持つこと。例えば「露」の「lù」は文言音、「lòu」は白話音。理論上、文言音は主に文言、詩歌、学術の分野に使っているが、白話音は生活のことを話すとき使う。標準中国語で一部の発音を取り除いた。例えば、もともと「白」は文言音「bó」と白話音「bái」と読むが、標準中国語で「bái」しか読まない。「露」の二つの発音も保留されたが、主に「lù」を使っている。「lòu」は指定された単語にしか使えない。これらの単語に「露」はすべて「動賓複合語」の動詞と扱っている（例えば「露面」は「顏を顕す」の意味）。「副露」はこれらの単語に指定されていない、さらに「動賓複合語」ではない。「副露」は中国語の辞書に収録されていないが、実際に中国のリーチ麻雀サークルには「fù lù」と読んでいる。ならば「副露」は「fù lù」と読むべきかと、私はそう考えている。
![lu](https://user-images.githubusercontent.com/29478770/189564822-79ed2b79-23f0-4754-83e7-924543bff695.jpg)

**Comment by kobalab** [comment]
指摘ありがとうございます。
誤記については修正しました。

fulou か fulu かに関しては、確かに fulu が正しい気もします(私が lou にしたのは “露马脚” からの連想)が、この名称は牌譜のプロパティ名として使用しているので互換性のために変更はしません。ご了承ください。
