### ISSUE TITLE
順位点の四捨五入について

### ISSUE THREAD

**Issue by TadaoYamaoka** [kobalab/majiang-core#7]
https://github.com/kobalab/majiang-core/blob/5a7132d30e7fc1d4011f7624459d4429fa2eecc9/lib/game.js#L673

上記のソースの箇所で、point[id]が、-19.5の場合、Math.round(point[id])は、-19になります。

Excelの「=ROUND(-19.5, 0)」では、-20で、
C++のstd::roundでも、-20になります。

負の数の0.5が切り下げられているのは正しい四捨五入処理でしょうか。

**Comment by kobalab** [comment]
回答が遅くなってすいません。気にしていませんでしたが、以前からこの動作でしたのでこのままとします。

**Comment by kidonaru** [comment]
こちらClose済みですが私も気になったので確認させてください。
このケースだと83800が93になって整合性取れてないように見えるのですが問題ないでしょうか?

https://github.com/kobalab/majiang-core/blob/7a934ea412dfddea9562fb627ac1f894e0291512/test/game.js#L1293-L1299

**Comment by kobalab** [comment]
問題ありません。

ここ(https://note.com/nemata3939/n/n12ed8f5e6063) にあるように、
> 麻雀の点数精算は、まずトップ以外の人の点数を計算して、その後総和が０になるようにトップの人に加算します。

がその理由です。
ただし、電脳麻将は端数は「五捨六入」ではなく、(かつての)天鳳同様に四捨五入しています。

**Comment by kidonaru** [comment]
返答ありがとうございます!

どうしても計算合わないなと思っていましたが、得点がプラスの場合は四捨五入、マイナスの場合は五捨六入というルールである、という見方をすれば問題はなさそうですね
納得しました!

**Comment by kidonaru** [comment]
あ、今頃ですがTwitter見ました…

たしかに質問の意図が分かりにくかったですね、すみません!

この質問をした意図がそもそもC#へ移植をしてるときに
テスト通らないので類似issue見かけて聞いてみた感じでした

https://github.com/kidonaru/majiang-core-unity/blob/f838b5bd9ffdbfb95a3a5ab2fee09a1462797915/Runtime/Game.cs#L1199-L1210
(プラスの場合は四捨五入、マイナスの場合は五捨六入でテストは無事通りました)


ついでにご連絡ですがmajiang-coreとmajiang-ai C#版公開しています

https://github.com/kidonaru/majiang-core-unity
https://github.com/kidonaru/majiang-ai-unity

なにか問題等あればご連絡お願いします!
